#!/usr/bin/env node

const { program } = require('commander');
const fs = require('fs');
const path = require('path');

program
  .name("cppkm")
  .version("1.0.0")
  .description("C++ Package Manager CLI");

program
  .command('init <project-name>')
  .description('Initialize a new C++ project')
  .action((name) => {
    const folder = path.join(process.cwd(), name);
    if (!fs.existsSync(folder)) fs.mkdirSync(folder);
    fs.mkdirSync(`${folder}/dependencies`, { recursive: true });

    fs.writeFileSync(`${folder}/pkg.json`, JSON.stringify({
      name,
      version: "1.0.0",
      dependencies: {}
    }, null, 2));

    fs.writeFileSync(`${folder}/README.md`, `# ${name}\n\nGenerated by cppkm.`);
    fs.writeFileSync(`${folder}/.gitignore.sample`, `dependencies/\n*.o\n*.exe\n`);

    console.log(`✅ Project '${name}' initialized.`);
  });

program.parse(process.argv);